### ISSUE TITLE
API 명세서 작성

### ISSUE THREAD

**Issue by seungy0** [boostcampwm2023/web04-ALGOCEAN#13]
**기능 소개**

### API 명세

![Image](https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/97934878/e3c440db-42cc-4920-af74-273987237bdd)

**TODO**

- [x] questions 관련 API 명세 작성
- [x] answers 관련 API 명세 작성
- [x] like 관련 API 명세 작성

**Comment by perArdua** [comment]
LGTM
