### ISSUE TITLE
React-Query 적용

### ISSUE THREAD

**Issue by BaeJ1H021** [boostcampwm2023/web04-ALGOCEAN#223]
**기능 소개**
서버 데이터 관리, 비동기 데이터 처리 간소화, 데이터 캐싱을 위해 React-Query 적용.

**TODO**
- [ ] useQuery, useMutate함수로 기존 비동기 데이터 처리 로직 간소화
- [ ] 서버 데이터와 클라이언트 데이터 분리
- [ ] 캐싱을 활용하여 빠른 로딩, 리소스 사용 최적화

**ETC**
