### ISSUE TITLE
메인 페이지 레이아웃

### ISSUE THREAD

**Issue by seungy0** [boostcampwm2023/web04-ALGOCEAN#23]
**기능 소개**

메인 페이지 레이아웃 구현

![image](https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/97934878/65194cce-84cc-434b-a972-98f30e6aae8f)

**TODO**
- [x] CSS 변수 설정
- [x] Main Header 구현
- [x] Nav 구현
- [x] 유니크 질문들 구현
- [x] 질문리스트 구현
- [x] 사용자 정보 컴포넌트 구현

**ETC**
