### ISSUE TITLE
CWV - 접근성 최적화

### ISSUE THREAD

**Issue by MayOwall** [boostcampwm2023/web04-ALGOCEAN#262]
**기능 소개**

웹 바이탈(CWV) 관련 접근성 최적화

**TODO**

- [ ] 이미지 요소에 alt 속성 부여
- [ ] 이미지 요소의 중복된 alt 속성 제거
- [ ] 백그라운드 및 포그라운드 색상의 대비율 증가
- [ ] 목록에 `<li>`요소와 스크립트 지원 요소만 포함되도록 작성
- [ ] 제목 요소가 내림차순으로 표시되도록 작성

**ETC**
