### ISSUE TITLE
Entity 생성

### ISSUE THREAD

**Issue by perArdua** [boostcampwm2023/web04-ALGOCEAN#45]
**기능 소개**
설계된 ERD를 기반으로 Prisma entity 생성

**TODO**
- [x] 질문 entity 생성
- [x] 답변 entity 생성
- [x] 유저 entity 생성
- [x] 유저_아이템 entity 생성
- [x] 아이템 entity 생성
- [x] 포인트_기록 entity 생성
- [x] 삭제_기록 entity 생성
- [x] 좋아요 entity 생성

Prisma 사용으로 대체
